oc:
  app:
    jwt:
      expirationMs: 86400000
      secret: ${TOKEN_SECRET}
spring:
  application:
    name: mdd-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: snake_case

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO
    com.openclassroom.mddapi: DEBUG